### ISSUE TITLE
Source check no longer returns known data

### ISSUE THREAD

**Issue by seth-rah** [soruly/trace.moe-telegram-bot#40]
## Summary

forwarded a post that I sent to the TG bot before, which it had a result for, but now no longer returns the result.

![image](https://user-images.githubusercontent.com/2222634/83924803-c8d34780-a785-11ea-9427-65477b5ea03a.png)

**Comment by tiaxter** [comment]
Now it works again! You can close the Issue!

**Comment by seth-rah** [comment]
That it does.
