### ISSUE TITLE
Better tutorial

### ISSUE THREAD

**Issue by F36** [soruly/trace.moe-telegram-bot#47]
Plz make a better tutorial on how to get all the env variables and how to start or deploy the bot

**Comment by soruly** [comment]
ya I think it's better to record a demo video and show them to new users. If I've time...

**Comment by F36** [comment]
yes that would be legendary ❤

**Comment by gabeklavans** [comment]
@F36  Just a note: if you set polling to true in the bot's options and remove the line passing in the webhook token, you can just define your own custom bot's Telegram API token in .env and have it working for local testing

**Comment by F36** [comment]
wll i am asking about getting env varibels

**Comment by soruly** [comment]
I've updated the README.md

**Comment by F36** [comment]
nice tutorial and with that i am closing this issue 

by - @F36
